version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_URL: http://192.168.178.100:9200
      ELASTICSEARCH_HOSTS: http://192.168.178.100:9200
    ports:
        - 5602:5601
    