version: '2'

services:
  es01:
    image: pestotoast/elasticsearch-armhf
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200

volumes:
    data01:
        driver: local